# Generated by Django 3.0a1 on 2020-01-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applyPage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btprequestentry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='btprequestentry',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='department',
        ),
        migrations.RemoveField(
            model_name='labrequestentry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='labrequestentry',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='othersrequestentry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='othersrequestentry',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.DeleteModel(
            name='BTP',
        ),
        migrations.DeleteModel(
            name='BTPRequestEntry',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
        migrations.DeleteModel(
            name='LabRequestEntry',
        ),
        migrations.DeleteModel(
            name='Other',
        ),
        migrations.DeleteModel(
            name='OthersRequestEntry',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
