# Generated by Django 3.0a1 on 2020-01-18 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applyPage', '0002_auto_20200119_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=264, unique=True)),
                ('hod_name', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=264, unique=True)),
                ('lab_name', models.CharField(max_length=264, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applyPage.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=264)),
                ('roll_number', models.IntegerField(unique=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=264, unique=True)),
                ('student_type', models.CharField(max_length=264)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applyPage.Department')),
            ],
        ),
        migrations.CreateModel(
            name='OthersRequestEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateField()),
                ('applied', models.BooleanField(default=False)),
                ('approved', models.PositiveSmallIntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=1000)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applyPage.Other')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applyPage.Student')),
            ],
        ),
        migrations.CreateModel(
            name='LabRequestEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateField()),
                ('applied', models.BooleanField()),
                ('approved', models.PositiveSmallIntegerField()),
                ('remark', models.CharField(blank=True, max_length=1000)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applyPage.Lab')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applyPage.Student')),
            ],
        ),
        migrations.CreateModel(
            name='BTPRequestEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateField()),
                ('applied', models.BooleanField(default=False)),
                ('approved', models.PositiveSmallIntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=1000)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applyPage.BTP')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applyPage.Student')),
            ],
        ),
        migrations.AddField(
            model_name='btp',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applyPage.Department'),
        ),
    ]
